package cn.stylefeng.guns.modular.form.entity;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * Table: t_log
 */
@Data
public class WbcLog implements Serializable {
    /**
     * Table:     t_log
     * Column:    id
     * Nullable:  false
     */
    private Long id;

    /**
     * Table:     t_log
     * Column:    Date
     * Nullable:  true
     */
    private Date date;

    /**
     * Table:     t_log
     * Column:    Thread
     * Nullable:  true
     */
    private String thread;

    /**
     * Table:     t_log
     * Column:    Level
     * Nullable:  true
     */
    private String level;

    /**
     * Table:     t_log
     * Column:    Logger
     * Nullable:  true
     */
    private String logger;

    /**
     * 操作项目标题
     *
     * Table:     t_log
     * Column:    title
     * Nullable:  true
     */
    private String title;

    /**
     * 1:插入 2:编辑 3：删除 ；4：查询
     *
     * Table:     t_log
     * Column:    type
     * Nullable:  true
     */
    private Integer type;

    /**
     * 操作人
     *
     * Table:     t_log
     * Column:    operUser
     * Nullable:  true
     */
    private String operuser;

    /**
     * Table:     t_log
     * Column:    code
     * Nullable:  true
     */
    private String code;

    /**
     * Table:     t_log
     * Column:    exceptionMsg
     * Nullable:  true
     */
    private String exceptionmsg;

    /**
     * 内容
     *
     * Table:     t_log
     * Column:    content
     * Nullable:  true
     */
    private String content;

    /**
     * Table:     t_log
     * Column:    memo
     * Nullable:  true
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_log
     *
     * @mbggenerated Sat Apr 25 14:18:55 CST 2020
     */
    private static final long serialVersionUID = 1L;
}