package cn.stylefeng.guns.modular.form.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import lombok.Data;

/**
 * Table: t_weigh_record
 */
@Data
public class WeighRecord implements Serializable {
    /**
     * Table:     t_weigh_record
     * Column:    id
     * Nullable:  false
     */
    private long id;

    /**
     * 车牌号
     *
     * Table:     t_weigh_record
     * Column:    plate_number
     * Nullable:  true
     */
    private String plateNumber;

    /**
     * 地磅编号
     *
     * Table:     t_weigh_record
     * Column:    weighbridge_code
     * Nullable:  true
     */
    private String weighbridgeCode;

    /**
     * 皮重
     *
     * Table:     t_weigh_record
     * Column:    tare
     * Nullable:  true
     */
    private BigDecimal tare;

    /**
     * 毛重
     *
     * Table:     t_weigh_record
     * Column:    gross
     * Nullable:  true
     */
    private BigDecimal gross;

    /**
     * 称重时间
     *
     * Table:     t_weigh_record
     * Column:    time_weigh
     * Nullable:  true
     */
    private Date timeWeigh;

    /**
     * 备用
     *
     * Table:     t_weigh_record
     * Column:    b1
     * Nullable:  true
     */
    private String b1;

    /**
     * 备用
     *
     * Table:     t_weigh_record
     * Column:    b2
     * Nullable:  true
     */
    private String b2;

    /**
     * 备用
     *
     * Table:     t_weigh_record
     * Column:    b3
     * Nullable:  true
     */
    private String b3;

    /**
     * 所属工区
     *
     * Table:     t_weigh_record
     * Column:    work_area
     * Nullable:  true
     */
    private String workArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_weigh_record
     *
     * @mbggenerated Thu Apr 30 08:59:01 CST 2020
     */
    private static final long serialVersionUID = 1L;
}
