package cn.stylefeng.guns.modular.form.entity;

import lombok.Data;

import java.io.Serializable;

/**
 * Table: t_weighbridge_config
 */
@Data
public class WeighbridgeConfig implements Serializable {
    /**
     * 自增长ID
     *
     * Table:     t_weighbridge_config
     * Column:    id
     * Nullable:  false
     */
    private Long id;

    /**
     * 地磅编号
     *
     * Table:     t_weighbridge_config
     * Column:    weightbridge_code
     * Nullable:  false
     */
    private String weightbridgeCode;

    /**
     * 地磅名称
     *
     * Table:     t_weighbridge_config
     * Column:    name
     * Nullable:  true
     */
    private String name;

    /**
     * 地磅类型
     *
     * Table:     t_weighbridge_config
     * Column:    type
     * Nullable:  true
     */
    private Integer type;

    /**
     * 称重上限
     *
     * Table:     t_weighbridge_config
     * Column:    toplimit
     * Nullable:  true
     */
    private Long toplimit;

    /**
     * 仪表IP地址
     *
     * Table:     t_weighbridge_config
     * Column:    ip_meter
     * Nullable:  true
     */
    private String ipMeter;

    /**
     * 车牌识别摄像机IP地址
     *
     * Table:     t_weighbridge_config
     * Column:    ip_camera
     * Nullable:  true
     */
    private String ipCamera;

    /**
     * LED指示牌IP地址
     *
     * Table:     t_weighbridge_config
     * Column:    ip_led
     * Nullable:  true
     */
    private String ipLed;

    /**
     * 是否可用：
1：可用
0：不可用
     *
     * Table:     t_weighbridge_config
     * Column:    available
     * Nullable:  true
     */
    private Integer available;

    /**
     * 是否在线
1：在线
0：离线
     *
     * Table:     t_weighbridge_config
     * Column:    is_online
     * Nullable:  true
     */
    private Integer isOnline;

    /**
     * Table:     t_weighbridge_config
     * Column:    b1
     * Nullable:  true
     */
    private String b1;

    /**
     * Table:     t_weighbridge_config
     * Column:    b2
     * Nullable:  true
     */
    private String b2;

    /**
     * Table:     t_weighbridge_config
     * Column:    b3
     * Nullable:  true
     */
    private String b3;

    /**
     * 起落杆ip地址
     */
    private String ipControlbox;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_weighbridge_config
     *
     * @mbggenerated Fri Apr 24 19:49:52 CST 2020
     */
    private static final long serialVersionUID = 1L;
}