package cn.stylefeng.guns.modular.form.model.example;

import java.util.ArrayList;
import java.util.List;

public class WeighbridgeConfigExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_weighbridge_config
     *
     * @mbggenerated Mon Apr 20 15:09:15 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_weighbridge_config
     *
     * @mbggenerated Mon Apr 20 15:09:15 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_weighbridge_config
     *
     * @mbggenerated Mon Apr 20 15:09:15 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weighbridge_config
     *
     * @mbggenerated Mon Apr 20 15:09:15 CST 2020
     */
    public WeighbridgeConfigExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weighbridge_config
     *
     * @mbggenerated Mon Apr 20 15:09:15 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weighbridge_config
     *
     * @mbggenerated Mon Apr 20 15:09:15 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weighbridge_config
     *
     * @mbggenerated Mon Apr 20 15:09:15 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weighbridge_config
     *
     * @mbggenerated Mon Apr 20 15:09:15 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weighbridge_config
     *
     * @mbggenerated Mon Apr 20 15:09:15 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weighbridge_config
     *
     * @mbggenerated Mon Apr 20 15:09:15 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weighbridge_config
     *
     * @mbggenerated Mon Apr 20 15:09:15 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weighbridge_config
     *
     * @mbggenerated Mon Apr 20 15:09:15 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weighbridge_config
     *
     * @mbggenerated Mon Apr 20 15:09:15 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weighbridge_config
     *
     * @mbggenerated Mon Apr 20 15:09:15 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_weighbridge_config
     *
     * @mbggenerated Mon Apr 20 15:09:15 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andWeightbridgeCodeIsNull() {
            addCriterion("weightbridge_code is null");
            return (Criteria) this;
        }

        public Criteria andWeightbridgeCodeIsNotNull() {
            addCriterion("weightbridge_code is not null");
            return (Criteria) this;
        }

        public Criteria andWeightbridgeCodeEqualTo(String value) {
            addCriterion("weightbridge_code =", value, "weightbridgeCode");
            return (Criteria) this;
        }

        public Criteria andWeightbridgeCodeNotEqualTo(String value) {
            addCriterion("weightbridge_code <>", value, "weightbridgeCode");
            return (Criteria) this;
        }

        public Criteria andWeightbridgeCodeGreaterThan(String value) {
            addCriterion("weightbridge_code >", value, "weightbridgeCode");
            return (Criteria) this;
        }

        public Criteria andWeightbridgeCodeGreaterThanOrEqualTo(String value) {
            addCriterion("weightbridge_code >=", value, "weightbridgeCode");
            return (Criteria) this;
        }

        public Criteria andWeightbridgeCodeLessThan(String value) {
            addCriterion("weightbridge_code <", value, "weightbridgeCode");
            return (Criteria) this;
        }

        public Criteria andWeightbridgeCodeLessThanOrEqualTo(String value) {
            addCriterion("weightbridge_code <=", value, "weightbridgeCode");
            return (Criteria) this;
        }

        public Criteria andWeightbridgeCodeLike(String value) {
            addCriterion("weightbridge_code like", value, "weightbridgeCode");
            return (Criteria) this;
        }

        public Criteria andWeightbridgeCodeNotLike(String value) {
            addCriterion("weightbridge_code not like", value, "weightbridgeCode");
            return (Criteria) this;
        }

        public Criteria andWeightbridgeCodeIn(List<String> values) {
            addCriterion("weightbridge_code in", values, "weightbridgeCode");
            return (Criteria) this;
        }

        public Criteria andWeightbridgeCodeNotIn(List<String> values) {
            addCriterion("weightbridge_code not in", values, "weightbridgeCode");
            return (Criteria) this;
        }

        public Criteria andWeightbridgeCodeBetween(String value1, String value2) {
            addCriterion("weightbridge_code between", value1, value2, "weightbridgeCode");
            return (Criteria) this;
        }

        public Criteria andWeightbridgeCodeNotBetween(String value1, String value2) {
            addCriterion("weightbridge_code not between", value1, value2, "weightbridgeCode");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andToplimitIsNull() {
            addCriterion("toplimit is null");
            return (Criteria) this;
        }

        public Criteria andToplimitIsNotNull() {
            addCriterion("toplimit is not null");
            return (Criteria) this;
        }

        public Criteria andToplimitEqualTo(Long value) {
            addCriterion("toplimit =", value, "toplimit");
            return (Criteria) this;
        }

        public Criteria andToplimitNotEqualTo(Long value) {
            addCriterion("toplimit <>", value, "toplimit");
            return (Criteria) this;
        }

        public Criteria andToplimitGreaterThan(Long value) {
            addCriterion("toplimit >", value, "toplimit");
            return (Criteria) this;
        }

        public Criteria andToplimitGreaterThanOrEqualTo(Long value) {
            addCriterion("toplimit >=", value, "toplimit");
            return (Criteria) this;
        }

        public Criteria andToplimitLessThan(Long value) {
            addCriterion("toplimit <", value, "toplimit");
            return (Criteria) this;
        }

        public Criteria andToplimitLessThanOrEqualTo(Long value) {
            addCriterion("toplimit <=", value, "toplimit");
            return (Criteria) this;
        }

        public Criteria andToplimitIn(List<Long> values) {
            addCriterion("toplimit in", values, "toplimit");
            return (Criteria) this;
        }

        public Criteria andToplimitNotIn(List<Long> values) {
            addCriterion("toplimit not in", values, "toplimit");
            return (Criteria) this;
        }

        public Criteria andToplimitBetween(Long value1, Long value2) {
            addCriterion("toplimit between", value1, value2, "toplimit");
            return (Criteria) this;
        }

        public Criteria andToplimitNotBetween(Long value1, Long value2) {
            addCriterion("toplimit not between", value1, value2, "toplimit");
            return (Criteria) this;
        }

        public Criteria andIpMeterIsNull() {
            addCriterion("ip_meter is null");
            return (Criteria) this;
        }

        public Criteria andIpMeterIsNotNull() {
            addCriterion("ip_meter is not null");
            return (Criteria) this;
        }

        public Criteria andIpMeterEqualTo(String value) {
            addCriterion("ip_meter =", value, "ipMeter");
            return (Criteria) this;
        }

        public Criteria andIpMeterNotEqualTo(String value) {
            addCriterion("ip_meter <>", value, "ipMeter");
            return (Criteria) this;
        }

        public Criteria andIpMeterGreaterThan(String value) {
            addCriterion("ip_meter >", value, "ipMeter");
            return (Criteria) this;
        }

        public Criteria andIpMeterGreaterThanOrEqualTo(String value) {
            addCriterion("ip_meter >=", value, "ipMeter");
            return (Criteria) this;
        }

        public Criteria andIpMeterLessThan(String value) {
            addCriterion("ip_meter <", value, "ipMeter");
            return (Criteria) this;
        }

        public Criteria andIpMeterLessThanOrEqualTo(String value) {
            addCriterion("ip_meter <=", value, "ipMeter");
            return (Criteria) this;
        }

        public Criteria andIpMeterLike(String value) {
            addCriterion("ip_meter like", value, "ipMeter");
            return (Criteria) this;
        }

        public Criteria andIpMeterNotLike(String value) {
            addCriterion("ip_meter not like", value, "ipMeter");
            return (Criteria) this;
        }

        public Criteria andIpMeterIn(List<String> values) {
            addCriterion("ip_meter in", values, "ipMeter");
            return (Criteria) this;
        }

        public Criteria andIpMeterNotIn(List<String> values) {
            addCriterion("ip_meter not in", values, "ipMeter");
            return (Criteria) this;
        }

        public Criteria andIpMeterBetween(String value1, String value2) {
            addCriterion("ip_meter between", value1, value2, "ipMeter");
            return (Criteria) this;
        }

        public Criteria andIpMeterNotBetween(String value1, String value2) {
            addCriterion("ip_meter not between", value1, value2, "ipMeter");
            return (Criteria) this;
        }

        public Criteria andIpCameraIsNull() {
            addCriterion("ip_camera is null");
            return (Criteria) this;
        }

        public Criteria andIpCameraIsNotNull() {
            addCriterion("ip_camera is not null");
            return (Criteria) this;
        }

        public Criteria andIpCameraEqualTo(String value) {
            addCriterion("ip_camera =", value, "ipCamera");
            return (Criteria) this;
        }

        public Criteria andIpCameraNotEqualTo(String value) {
            addCriterion("ip_camera <>", value, "ipCamera");
            return (Criteria) this;
        }

        public Criteria andIpCameraGreaterThan(String value) {
            addCriterion("ip_camera >", value, "ipCamera");
            return (Criteria) this;
        }

        public Criteria andIpCameraGreaterThanOrEqualTo(String value) {
            addCriterion("ip_camera >=", value, "ipCamera");
            return (Criteria) this;
        }

        public Criteria andIpCameraLessThan(String value) {
            addCriterion("ip_camera <", value, "ipCamera");
            return (Criteria) this;
        }

        public Criteria andIpCameraLessThanOrEqualTo(String value) {
            addCriterion("ip_camera <=", value, "ipCamera");
            return (Criteria) this;
        }

        public Criteria andIpCameraLike(String value) {
            addCriterion("ip_camera like", value, "ipCamera");
            return (Criteria) this;
        }

        public Criteria andIpCameraNotLike(String value) {
            addCriterion("ip_camera not like", value, "ipCamera");
            return (Criteria) this;
        }

        public Criteria andIpCameraIn(List<String> values) {
            addCriterion("ip_camera in", values, "ipCamera");
            return (Criteria) this;
        }

        public Criteria andIpCameraNotIn(List<String> values) {
            addCriterion("ip_camera not in", values, "ipCamera");
            return (Criteria) this;
        }

        public Criteria andIpCameraBetween(String value1, String value2) {
            addCriterion("ip_camera between", value1, value2, "ipCamera");
            return (Criteria) this;
        }

        public Criteria andIpCameraNotBetween(String value1, String value2) {
            addCriterion("ip_camera not between", value1, value2, "ipCamera");
            return (Criteria) this;
        }

        public Criteria andIpLedIsNull() {
            addCriterion("ip_led is null");
            return (Criteria) this;
        }

        public Criteria andIpLedIsNotNull() {
            addCriterion("ip_led is not null");
            return (Criteria) this;
        }

        public Criteria andIpLedEqualTo(String value) {
            addCriterion("ip_led =", value, "ipLed");
            return (Criteria) this;
        }

        public Criteria andIpLedNotEqualTo(String value) {
            addCriterion("ip_led <>", value, "ipLed");
            return (Criteria) this;
        }

        public Criteria andIpLedGreaterThan(String value) {
            addCriterion("ip_led >", value, "ipLed");
            return (Criteria) this;
        }

        public Criteria andIpLedGreaterThanOrEqualTo(String value) {
            addCriterion("ip_led >=", value, "ipLed");
            return (Criteria) this;
        }

        public Criteria andIpLedLessThan(String value) {
            addCriterion("ip_led <", value, "ipLed");
            return (Criteria) this;
        }

        public Criteria andIpLedLessThanOrEqualTo(String value) {
            addCriterion("ip_led <=", value, "ipLed");
            return (Criteria) this;
        }

        public Criteria andIpLedLike(String value) {
            addCriterion("ip_led like", value, "ipLed");
            return (Criteria) this;
        }

        public Criteria andIpLedNotLike(String value) {
            addCriterion("ip_led not like", value, "ipLed");
            return (Criteria) this;
        }

        public Criteria andIpLedIn(List<String> values) {
            addCriterion("ip_led in", values, "ipLed");
            return (Criteria) this;
        }

        public Criteria andIpLedNotIn(List<String> values) {
            addCriterion("ip_led not in", values, "ipLed");
            return (Criteria) this;
        }

        public Criteria andIpLedBetween(String value1, String value2) {
            addCriterion("ip_led between", value1, value2, "ipLed");
            return (Criteria) this;
        }

        public Criteria andIpLedNotBetween(String value1, String value2) {
            addCriterion("ip_led not between", value1, value2, "ipLed");
            return (Criteria) this;
        }

        public Criteria andAvailableIsNull() {
            addCriterion("available is null");
            return (Criteria) this;
        }

        public Criteria andAvailableIsNotNull() {
            addCriterion("available is not null");
            return (Criteria) this;
        }

        public Criteria andAvailableEqualTo(Integer value) {
            addCriterion("available =", value, "available");
            return (Criteria) this;
        }

        public Criteria andAvailableNotEqualTo(Integer value) {
            addCriterion("available <>", value, "available");
            return (Criteria) this;
        }

        public Criteria andAvailableGreaterThan(Integer value) {
            addCriterion("available >", value, "available");
            return (Criteria) this;
        }

        public Criteria andAvailableGreaterThanOrEqualTo(Integer value) {
            addCriterion("available >=", value, "available");
            return (Criteria) this;
        }

        public Criteria andAvailableLessThan(Integer value) {
            addCriterion("available <", value, "available");
            return (Criteria) this;
        }

        public Criteria andAvailableLessThanOrEqualTo(Integer value) {
            addCriterion("available <=", value, "available");
            return (Criteria) this;
        }

        public Criteria andAvailableIn(List<Integer> values) {
            addCriterion("available in", values, "available");
            return (Criteria) this;
        }

        public Criteria andAvailableNotIn(List<Integer> values) {
            addCriterion("available not in", values, "available");
            return (Criteria) this;
        }

        public Criteria andAvailableBetween(Integer value1, Integer value2) {
            addCriterion("available between", value1, value2, "available");
            return (Criteria) this;
        }

        public Criteria andAvailableNotBetween(Integer value1, Integer value2) {
            addCriterion("available not between", value1, value2, "available");
            return (Criteria) this;
        }

        public Criteria andIsOnlineIsNull() {
            addCriterion("is_online is null");
            return (Criteria) this;
        }

        public Criteria andIsOnlineIsNotNull() {
            addCriterion("is_online is not null");
            return (Criteria) this;
        }

        public Criteria andIsOnlineEqualTo(Integer value) {
            addCriterion("is_online =", value, "isOnline");
            return (Criteria) this;
        }

        public Criteria andIsOnlineNotEqualTo(Integer value) {
            addCriterion("is_online <>", value, "isOnline");
            return (Criteria) this;
        }

        public Criteria andIsOnlineGreaterThan(Integer value) {
            addCriterion("is_online >", value, "isOnline");
            return (Criteria) this;
        }

        public Criteria andIsOnlineGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_online >=", value, "isOnline");
            return (Criteria) this;
        }

        public Criteria andIsOnlineLessThan(Integer value) {
            addCriterion("is_online <", value, "isOnline");
            return (Criteria) this;
        }

        public Criteria andIsOnlineLessThanOrEqualTo(Integer value) {
            addCriterion("is_online <=", value, "isOnline");
            return (Criteria) this;
        }

        public Criteria andIsOnlineIn(List<Integer> values) {
            addCriterion("is_online in", values, "isOnline");
            return (Criteria) this;
        }

        public Criteria andIsOnlineNotIn(List<Integer> values) {
            addCriterion("is_online not in", values, "isOnline");
            return (Criteria) this;
        }

        public Criteria andIsOnlineBetween(Integer value1, Integer value2) {
            addCriterion("is_online between", value1, value2, "isOnline");
            return (Criteria) this;
        }

        public Criteria andIsOnlineNotBetween(Integer value1, Integer value2) {
            addCriterion("is_online not between", value1, value2, "isOnline");
            return (Criteria) this;
        }

        public Criteria andB1IsNull() {
            addCriterion("b1 is null");
            return (Criteria) this;
        }

        public Criteria andB1IsNotNull() {
            addCriterion("b1 is not null");
            return (Criteria) this;
        }

        public Criteria andB1EqualTo(String value) {
            addCriterion("b1 =", value, "b1");
            return (Criteria) this;
        }

        public Criteria andB1NotEqualTo(String value) {
            addCriterion("b1 <>", value, "b1");
            return (Criteria) this;
        }

        public Criteria andB1GreaterThan(String value) {
            addCriterion("b1 >", value, "b1");
            return (Criteria) this;
        }

        public Criteria andB1GreaterThanOrEqualTo(String value) {
            addCriterion("b1 >=", value, "b1");
            return (Criteria) this;
        }

        public Criteria andB1LessThan(String value) {
            addCriterion("b1 <", value, "b1");
            return (Criteria) this;
        }

        public Criteria andB1LessThanOrEqualTo(String value) {
            addCriterion("b1 <=", value, "b1");
            return (Criteria) this;
        }

        public Criteria andB1Like(String value) {
            addCriterion("b1 like", value, "b1");
            return (Criteria) this;
        }

        public Criteria andB1NotLike(String value) {
            addCriterion("b1 not like", value, "b1");
            return (Criteria) this;
        }

        public Criteria andB1In(List<String> values) {
            addCriterion("b1 in", values, "b1");
            return (Criteria) this;
        }

        public Criteria andB1NotIn(List<String> values) {
            addCriterion("b1 not in", values, "b1");
            return (Criteria) this;
        }

        public Criteria andB1Between(String value1, String value2) {
            addCriterion("b1 between", value1, value2, "b1");
            return (Criteria) this;
        }

        public Criteria andB1NotBetween(String value1, String value2) {
            addCriterion("b1 not between", value1, value2, "b1");
            return (Criteria) this;
        }

        public Criteria andB2IsNull() {
            addCriterion("b2 is null");
            return (Criteria) this;
        }

        public Criteria andB2IsNotNull() {
            addCriterion("b2 is not null");
            return (Criteria) this;
        }

        public Criteria andB2EqualTo(String value) {
            addCriterion("b2 =", value, "b2");
            return (Criteria) this;
        }

        public Criteria andB2NotEqualTo(String value) {
            addCriterion("b2 <>", value, "b2");
            return (Criteria) this;
        }

        public Criteria andB2GreaterThan(String value) {
            addCriterion("b2 >", value, "b2");
            return (Criteria) this;
        }

        public Criteria andB2GreaterThanOrEqualTo(String value) {
            addCriterion("b2 >=", value, "b2");
            return (Criteria) this;
        }

        public Criteria andB2LessThan(String value) {
            addCriterion("b2 <", value, "b2");
            return (Criteria) this;
        }

        public Criteria andB2LessThanOrEqualTo(String value) {
            addCriterion("b2 <=", value, "b2");
            return (Criteria) this;
        }

        public Criteria andB2Like(String value) {
            addCriterion("b2 like", value, "b2");
            return (Criteria) this;
        }

        public Criteria andB2NotLike(String value) {
            addCriterion("b2 not like", value, "b2");
            return (Criteria) this;
        }

        public Criteria andB2In(List<String> values) {
            addCriterion("b2 in", values, "b2");
            return (Criteria) this;
        }

        public Criteria andB2NotIn(List<String> values) {
            addCriterion("b2 not in", values, "b2");
            return (Criteria) this;
        }

        public Criteria andB2Between(String value1, String value2) {
            addCriterion("b2 between", value1, value2, "b2");
            return (Criteria) this;
        }

        public Criteria andB2NotBetween(String value1, String value2) {
            addCriterion("b2 not between", value1, value2, "b2");
            return (Criteria) this;
        }

        public Criteria andB3IsNull() {
            addCriterion("b3 is null");
            return (Criteria) this;
        }

        public Criteria andB3IsNotNull() {
            addCriterion("b3 is not null");
            return (Criteria) this;
        }

        public Criteria andB3EqualTo(String value) {
            addCriterion("b3 =", value, "b3");
            return (Criteria) this;
        }

        public Criteria andB3NotEqualTo(String value) {
            addCriterion("b3 <>", value, "b3");
            return (Criteria) this;
        }

        public Criteria andB3GreaterThan(String value) {
            addCriterion("b3 >", value, "b3");
            return (Criteria) this;
        }

        public Criteria andB3GreaterThanOrEqualTo(String value) {
            addCriterion("b3 >=", value, "b3");
            return (Criteria) this;
        }

        public Criteria andB3LessThan(String value) {
            addCriterion("b3 <", value, "b3");
            return (Criteria) this;
        }

        public Criteria andB3LessThanOrEqualTo(String value) {
            addCriterion("b3 <=", value, "b3");
            return (Criteria) this;
        }

        public Criteria andB3Like(String value) {
            addCriterion("b3 like", value, "b3");
            return (Criteria) this;
        }

        public Criteria andB3NotLike(String value) {
            addCriterion("b3 not like", value, "b3");
            return (Criteria) this;
        }

        public Criteria andB3In(List<String> values) {
            addCriterion("b3 in", values, "b3");
            return (Criteria) this;
        }

        public Criteria andB3NotIn(List<String> values) {
            addCriterion("b3 not in", values, "b3");
            return (Criteria) this;
        }

        public Criteria andB3Between(String value1, String value2) {
            addCriterion("b3 between", value1, value2, "b3");
            return (Criteria) this;
        }

        public Criteria andB3NotBetween(String value1, String value2) {
            addCriterion("b3 not between", value1, value2, "b3");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_weighbridge_config
     *
     * @mbggenerated do_not_delete_during_merge Mon Apr 20 15:09:15 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_weighbridge_config
     *
     * @mbggenerated Mon Apr 20 15:09:15 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}