package cn.stylefeng.guns.modular.form.mapper;

import cn.stylefeng.guns.modular.form.entity.Vehicle;
import cn.stylefeng.guns.modular.form.entity.VehicleExample;
import java.util.List;
import java.util.Map;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface VehicleMapper  extends BaseMapper<Vehicle> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vehicle
     *
     * @mbggenerated Thu Apr 23 17:18:18 CST 2020
     */
    int countByExample(VehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vehicle
     *
     * @mbggenerated Thu Apr 23 17:18:18 CST 2020
     */
    int deleteByExample(VehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vehicle
     *
     * @mbggenerated Thu Apr 23 17:18:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vehicle
     *
     * @mbggenerated Thu Apr 23 17:18:18 CST 2020
     */
    int insert(Vehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vehicle
     *
     * @mbggenerated Thu Apr 23 17:18:18 CST 2020
     */
    int insertSelective(Vehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vehicle
     *
     * @mbggenerated Thu Apr 23 17:18:18 CST 2020
     */
    List<Vehicle> selectByExampleWithRowbounds(VehicleExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vehicle
     *
     * @mbggenerated Thu Apr 23 17:18:18 CST 2020
     */
    List<Vehicle> selectByExample(VehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vehicle
     *
     * @mbggenerated Thu Apr 23 17:18:18 CST 2020
     */
    Vehicle selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vehicle
     *
     * @mbggenerated Thu Apr 23 17:18:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") Vehicle record, @Param("example") VehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vehicle
     *
     * @mbggenerated Thu Apr 23 17:18:18 CST 2020
     */
    int updateByExample(@Param("record") Vehicle record, @Param("example") VehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vehicle
     *
     * @mbggenerated Thu Apr 23 17:18:18 CST 2020
     */
    int updateByPrimaryKeySelective(Vehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vehicle
     *
     * @mbggenerated Thu Apr 23 17:18:18 CST 2020
     */
    int updateByPrimaryKey(Vehicle record);

    /**
     * 查询
     */
    Page<Map<String, Object>> queryVehicle(@Param("page") Page page, @Param("plateNumber") String plateNumber,@Param("vehicleType") String vehicleType,@Param("workArea") String workArea);

    List<Vehicle> selectByWorkArea(@Param("workArea") String workArea);

    List<Vehicle> getCarsExcel(@Param("plateNumber") String plateNumber,@Param("vehicleType") String vehicleType,@Param("workArea") String workArea);
}