package cn.stylefeng.guns.modular.form.mapper;

import cn.stylefeng.guns.modular.form.entity.WbcLog;
import cn.stylefeng.guns.modular.form.entity.WbcLogExample;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;
import java.util.Map;

public interface WbcLogMapper extends BaseMapper<WbcLog> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbggenerated Sat Apr 25 14:18:55 CST 2020
     */
    int countByExample(WbcLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbggenerated Sat Apr 25 14:18:55 CST 2020
     */
    int deleteByExample(WbcLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbggenerated Sat Apr 25 14:18:55 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbggenerated Sat Apr 25 14:18:55 CST 2020
     */
    int insert(WbcLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbggenerated Sat Apr 25 14:18:55 CST 2020
     */
    int insertSelective(WbcLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbggenerated Sat Apr 25 14:18:55 CST 2020
     */
    List<WbcLog> selectByExampleWithBLOBsWithRowbounds(WbcLogExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbggenerated Sat Apr 25 14:18:55 CST 2020
     */
    List<WbcLog> selectByExampleWithBLOBs(WbcLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbggenerated Sat Apr 25 14:18:55 CST 2020
     */
    List<WbcLog> selectByExampleWithRowbounds(WbcLogExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbggenerated Sat Apr 25 14:18:55 CST 2020
     */
    List<WbcLog> selectByExample(WbcLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbggenerated Sat Apr 25 14:18:55 CST 2020
     */
    WbcLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbggenerated Sat Apr 25 14:18:55 CST 2020
     */
    int updateByExampleSelective(@Param("record") WbcLog record, @Param("example") WbcLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbggenerated Sat Apr 25 14:18:55 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") WbcLog record, @Param("example") WbcLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbggenerated Sat Apr 25 14:18:55 CST 2020
     */
    int updateByExample(@Param("record") WbcLog record, @Param("example") WbcLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbggenerated Sat Apr 25 14:18:55 CST 2020
     */
    int updateByPrimaryKeySelective(WbcLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbggenerated Sat Apr 25 14:18:55 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(WbcLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbggenerated Sat Apr 25 14:18:55 CST 2020
     */
    int updateByPrimaryKey(WbcLog record);


    Page<Map<String, Object>> queryDataLog(@Param("page") Page page, @Param("beginTime") String beginTime, @Param("endTime") String endTime);
}