package cn.stylefeng.guns.modular.form.mapper;

import cn.stylefeng.guns.Model.Weighbridge_Model;
import cn.stylefeng.guns.modular.form.entity.WeighbridgeConfig;
import cn.stylefeng.guns.modular.form.entity.WeighbridgeConfigExample;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;
import java.util.Map;

public interface WeighbridgeConfigMapper extends BaseMapper<WeighbridgeConfig> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weighbridge_config
     *
     * @mbggenerated Fri Apr 24 19:49:52 CST 2020
     */
    int countByExample(WeighbridgeConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weighbridge_config
     *
     * @mbggenerated Fri Apr 24 19:49:52 CST 2020
     */
    int deleteByExample(WeighbridgeConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weighbridge_config
     *
     * @mbggenerated Fri Apr 24 19:49:52 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weighbridge_config
     *
     * @mbggenerated Fri Apr 24 19:49:52 CST 2020
     */
    int insert(WeighbridgeConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weighbridge_config
     *
     * @mbggenerated Fri Apr 24 19:49:52 CST 2020
     */
    int insertSelective(WeighbridgeConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weighbridge_config
     *
     * @mbggenerated Fri Apr 24 19:49:52 CST 2020
     */
    List<WeighbridgeConfig> selectByExampleWithRowbounds(WeighbridgeConfigExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weighbridge_config
     *
     * @mbggenerated Fri Apr 24 19:49:52 CST 2020
     */
    List<WeighbridgeConfig> selectByExample(WeighbridgeConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weighbridge_config
     *
     * @mbggenerated Fri Apr 24 19:49:52 CST 2020
     */
    WeighbridgeConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weighbridge_config
     *
     * @mbggenerated Fri Apr 24 19:49:52 CST 2020
     */
    int updateByExampleSelective(@Param("record") WeighbridgeConfig record, @Param("example") WeighbridgeConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weighbridge_config
     *
     * @mbggenerated Fri Apr 24 19:49:52 CST 2020
     */
    int updateByExample(@Param("record") WeighbridgeConfig record, @Param("example") WeighbridgeConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weighbridge_config
     *
     * @mbggenerated Fri Apr 24 19:49:52 CST 2020
     */
    int updateByPrimaryKeySelective(WeighbridgeConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weighbridge_config
     *
     * @mbggenerated Fri Apr 24 19:49:52 CST 2020
     */
    int updateByPrimaryKey(WeighbridgeConfig record);

    /**
     * 查询
     */
    Page<Map<String, Object>> selectWbc(@Param("page") Page page);
    List<WeighbridgeConfig> GetConfigList();

    List<WeighbridgeConfig> getAllIpCamera();
}
